name: Plugin
version: '${project.version}'
main: com.plugin.baseplugin.Plugin
api-version: 1.18
description: Base of plugin minecraft

commands:
  msgClient:
    aliases:
      - 'client'
      - 'msgClient'
    description: "Send a message to client"


